version: "3.3"

services:

  traefik:
    build: 
      context: .
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--entryPoints.http.address=:9000"
      - "--entryPoints.http.forwardedHeaders.insecure=true"
      - "--experimental.localPlugins.demo.moduleName=github.com/DoVietHoang1712/demo"
      - "--log.level=DEBUG"
      - "--providers.file.filename=/plugins-local/src/github.com/DoVietHoang1712/demo/rules-demo.yaml"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    ports:
      - "5000:80"
    labels:
      - "traefik.enable=true"
    #   - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
    #   - "traefik.http.routers.whoami.entrypoints=web"